### ISSUE TITLE
switch from coffeescript to javascript

### ISSUE THREAD

**Issue by jimmywarting** [fedwiki/wiki-server#163]
Javascript have modernised
it has many new features like top level await, ESM, classes, null assignment, optional chaining, etc

**Comment by WardCunningham** [comment]
We are big fans of modern javascript.

We have the freedom to employ whatever technology we might prefer since servers only talk to their own clients and it is the clients that talk to the rest of the federation fetching inert json via cross-origin resource sharing gets. Our first year was based in ruby with a small remote sensing version written in c++. We switched to node when @nrn showed that he could pass all of our tests with his solo effort in node. The ruby version is still serving at least one site but we discourage its use and have archived its repo.

https://github.com/WardCunningham/Smallest-Federated-Wiki/tree/master/server

We talk about innovation in terms of "outposts" where servers can be quite different but still maintain links with the federation. 

http://ward.asia.wiki.org/outpost-thinking.html

We've been building outposts in modern javascript since Ryan Dahl convinced us that ES6 modules are the right way to configure servers. Our current work is more focused on enhancing the client side with advanced discovery mechanisms, async signaling, and, of special interest to me, integrated functional testing.  

http://found.ward.bay.wiki.org/nodes-mistakes.html

Coffeescript has served us well with node on the server and jQuery on the client. Today we are building the replacement for all three with the intention that it will fuel our next decade. I will close this issue but would be happy to keep this conversation going if you are thinking you would like to contribute to our next adventure.
