### ISSUE TITLE
How to specify admin in config.json with "security_type": "friends"

### ISSUE THREAD

**Issue by rybesh** [fedwiki/wiki-server#167]
I am running a local fedwiki with "security_type": "friends" in my config.json.

I would like to make myself admin so that I can install plugins. How do I do that? “The admin value would depend on how individuals are identified by the security module in use,” but no example is given for "security_type": "friends".

**Comment by rybesh** [comment]
I was looking at http://fedwiki.org/view/admin-user

I'm not using a docker image.

Here's my setup:
```
$ cat ~/.wiki/config.json
{
  "security_type": "friends",
  "cookieSecret": "[REDACTED COOKIE SECRET]",
  "session_duration": 365
}
$ cat ~/.wiki/status/owner.json
{
  "name": "Ryan Shaw",
  "friend": {
    "secret": "[REDACTED SECRET]"
  }
}
```

The example at http://fedwiki.org/view/admin-user says to add to `config.json` the following:
```json
"admin": {"google": "1234xxxxxxxxxx"},
```

I'm unclear whether the `friends` equivalent would be:

```json
"admin": "[REDACTED SECRET]",
```

or 

```json
"admin": {"secret": "[REDACTED SECRET]"},
```

or

```json
"admin": {"friend": {"secret": "[REDACTED SECRET]"}},
```

or 

```json
"admin": {"friends": {"secret": "[REDACTED SECRET]"}},
```

or some other variation I haven't thought of yet.

Part of the problem may be that I don't know how to test whether I am successfully logging in as an admin.

**Comment by WardCunningham** [comment]
I regret that I am unsure of the answer because I am not sure what path this information takes through the code. I believe you want the config file equivalent of the command line parameter `--admin 098034982034`

I will consult other developers to see if I can come up with a more definitive answer and make sure it is well documented. Many of our user/administrators write about what has worked for them and that is the case for the page you cite. It is also the case for me above because I just looked at the one site I have that uses friends without a full understanding of what is possible.

**Comment by WardCunningham** [comment]
We should be able to do better than this.
